services:
  gpt-service:
    build:
      context: .
      dockerfile: services/gpt-context/Dockerfile
    restart: unless-stopped
    expose:
      - 50051
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      WEAVIATE_URL: ${WEAVIATE_URL}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      GOOGLE_APPLICATION_TOKEN: ${GOOGLE_APPLICATION_TOKEN}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./services/gpt-context/source_documents:/app/source_documents
      - ./services/gpt-context/.credentials:/app/.credentials
    depends_on:
      - weaviate
      - conversation-store

  telegram-bot:
    build:
      context: .
      dockerfile: services/telegram-bot/Dockerfile
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      GPT_SERVICE_ADDRESS: gpt-service:50051
      CONTEXT_NAME: default
      APP_ENV: production
    depends_on:
      - gpt-service
  instagram_service:
    build:
      context: .
      dockerfile: services/instagram_service/Dockerfile
    restart: unless-stopped
    environment:
      GPT_SERVICE_ADDRESS: gpt-service:50051
      PASSWORD: ${PASSWORD}
      USER_NAME: ${USER_NAME}
      PROXY: ${PROXY}
      TARGET: ${TARGET}
      CONVERSATION_ID: ${CONVERSATION_ID}
      CONTEXT_NAME: ${CONTEXT_NAME}
    depends_on:
      - gpt-service

  weaviate:
    image: semitechnologies/weaviate:1.19.6
    expose:
      - 8080
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate-data:/var/lib/weaviate

  conversation-store:
    image: mongo:6.0.7
    expose:
      - 27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - conversation-store-data:/data/db

  healthcheck:
    image: louislam/uptime-kuma:1
    ports:
      - 3001:3001
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - healthcheck-data:/app/data

volumes:
  conversation-store-data:
  redis-cache-data:
  weaviate-data:
  healthcheck-data:
